external_components:
- source: github://chadmatsalla/esphome_components
  refresh: 10s
  components:
    - acs712

esphome:
  name: acs
  friendly_name: "ACS712"
  libraries:
    - https://github.com/RobTillaart/ACS712.git

api:

logger:
  level: DEBUG

sensor:
- id: csmacs
  name: "Dieselwurks Sensor"
  platform: acs712
  # csmpin: 0
  # pin: GPIO0
  current:
    name: "Current"
    id: current
    unit_of_measurement: A
    accuracy_decimals: 2
  power:
    name: "Watts"
    id: watts
    unit_of_measurement: W
    accuracy_decimals: 2
  update_interval: 5s
