external_components:
# - source: github://chadmatsalla/esphome_components
#  refresh: 10s
#  components:
#    - acs712
- source:
    type: local
    path: ~/git-controlled/esphome_components/components

esphome:
  name: acs
  friendly_name: "ACS712"
  # libraries:
  #   - https://github.com/RobTillaart/ACS712.git



logger:
  level: DEBUG

sensor:
- id: csmacs
  name: "Dieselwurks Sensor"
  platform: acs712
  sensor: ads1115_a0
  update_interval: 5s
  midpoint: 1.65
  max_volts: 3.08
  max_amps: 5
  # csmpin: 0
  # pin: GPIO0
#  current:
#    name: "Current"
#    id: current
#    unit_of_measurement: A
#    accuracy_decimals: 2
#  power:
#    name: "Watts"
#    id: watts
#    unit_of_measurement: W
#    accuracy_decimals: 2
