esp32:
  board: seeed_xiao_esp32c3

packages:
  acs712: !include acs712.yml

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: True

# api:

logger:
  level: DEBUG
  logs:
    sensor: info

select:
  - platform: logger
    name: "Logger select"

ads1115:
- id: ads1115_1
  address: 0x48

sensor:
#- platform: adc
#  pin: GPIO0
#  name: "ACS712"
#  id: acs712_1
#  update_interval: 5s
- platform: ads1115
  multiplexer: 'A0_GND'
  gain: 4.096
  name: "ADS1115 A0"
  id: ads1115_a0
  update_interval: 30s
  
#web_server:
#  version: 3

#ota:
#  platform: esphome
  
# wifi:
#  networks:
#  - ssid: !secret ssid
#    password: !secret password
#  - ssid: !secret ssid2
#    password: !secret password2